markdown: kramdown
kramdown: 
  toc_levels: "1,2,3"

# references jekyll-scholar
scholar:
    replace_strings: true
    query: "@*"
    bibliography: references.bib
    # style: apa

collections:
    topic:
        output: true
        permalink: /topic/:name
      #    people: true

        # You can define default values for attributes on topics. This can be useful if all the documents in the collection will share the same layout for example:
defaults:
  - scope:
      path: ""
      type: "topic"
    values:
      layout: topic

